#pipeline 
name: CICD-pipeline-for-a-travel-memory-application
on:
  push:
    branches:
      - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Connecting to EC2
            uses: appleboy/ssh-action@v1.0.3
            with:
                   host: ${{ secrets.EC2_HOST }}
                   username: ${{ secrets.EC2_USERNAME }}
                   key: ${{ secrets.EC2_SSH_KEY }}
                   port: 22
                   script: |
                        whoami
                        sudo apt-get update -y
                        sudo apt-get install nginx -y
    
